CREATE DATABASE voting;
\c voting;
CREATE TABLE users(USN CHAR(20) PRIMARY KEY  NOT NULL, NAME CHAR(20) NOT NULL UNIQUE, ROLE CHAR(20));
CREATE TABLE registered_phones( PHONE_ID CHAR(20) PRIMARY KEY  NOT NULL, ISVERIFIED BOOLEAN, REGISTERED_AT BIGINT);
CREATE TABLE attendance( ID VARCHAR(100) PRIMARY KEY  NOT NULL,USN CHAR(20) NOT NULL,PHONE_ID CHAR(20) references registered_phones(PHONE_ID),LAST_MODIFIED_AT BIGINT);
CREATE TABLE teams( ID CHAR(100) PRIMARY KEY  NOT NULL, NAME CHAR(100) UNIQUE, PHOTO_URL CHAR(50),DESCRIPTION VARCHAR(1000),CREATED_AT BIGINT);
CREATE TABLE votes(ID VARCHAR(100) PRIMARY KEY NOT NULL, USN CHAR(20) NOT NULL references users(USN),TEAM_ID CHAR(20) NOT NULL, timestamp BIGINT);
CREATE TABLE nonce( UUID CHAR(100) PRIMARY KEY NOT NULL, COUNT INT,  TIME_LOG BIGINT);
CREATE TABLE sessions( TOKEN CHAR(500) PRIMARY KEY NOT NULL, TIME_LOG BIGINT, PAYLOAD CHAR(400), SIGNATURE CHAR(400),UUID CHAR(400));